import type { Product } from '../types'

export const DEV_CATALOGUE: Product[] = [
  {
    id: 'dev-starter-1200-2000-800',
    title: 'Starter Bay — Steel Panels 1200×2000×800mm',
    handle: 'starter-steel-panels-1200-2000-800',
    imageUrl: null,
    objectType: 'starter',
    variants: [
      {
        id: 'var-LSS2012803S',
        sku: 'LSS2012803S',
        price: 325.00,
        availableForSale: true,
        width: 1200,
        height: 2000,
        depth: 800,
        numberOfShelves: 3,
        numberOfLevels: 5,
        kgPerShelf: 500,
        frameMaterial: 'Steel',
        frameCoating: 'Powder Coated',
        shelfType: 'Steel Panels',
        compatibleShelfSku: 'LSSL12801L',
      },
    ],
  },
  {
    id: 'dev-extender-1200-2000-800',
    title: 'Extender Bay — Steel Panels 1200×2000×800mm',
    handle: 'extender-steel-panels-1200-2000-800',
    imageUrl: null,
    objectType: 'extender',
    variants: [
      {
        id: 'var-LSS2012803X',
        sku: 'LSS2012803X',
        price: 280.00,
        availableForSale: true,
        width: 1200,
        height: 2000,
        depth: 800,
        numberOfShelves: 3,
        numberOfLevels: 5,
        kgPerShelf: 500,
        frameMaterial: 'Steel',
        frameCoating: 'Powder Coated',
        shelfType: 'Steel Panels',
        compatibleShelfSku: 'LSSL12801L',
      },
    ],
  },
  {
    id: 'dev-shelf-1200-800',
    title: 'Extra Level Shelf — Steel Panel 1200×800mm',
    handle: 'extra-level-shelf-steel-panel-1200-800',
    imageUrl: null,
    objectType: 'shelf',
    variants: [
      {
        id: 'var-LSSL12801L',
        sku: 'LSSL12801L',
        price: 105.00,
        availableForSale: true,
        width: 1200,
        height: 0,
        depth: 800,
        numberOfShelves: 1,
        numberOfLevels: 1,
        kgPerShelf: 500,
        frameMaterial: 'Steel',
        frameCoating: 'Powder Coated',
        shelfType: 'Steel Panels',
        compatibleShelfSku: null,
      },
    ],
  },
  {
    id: 'dev-accessory-picking-station',
    title: 'Picking Station — Accessory 1200×2000×300mm',
    handle: 'picking-station-1200-2000-300',
    imageUrl: null,
    objectType: 'accessory',
    variants: [
      {
        id: 'var-LSPS1230',
        sku: 'LSPS1230',
        price: 0,
        availableForSale: true,
        width: 1200,
        height: 2000,
        depth: 300,
        numberOfShelves: 1,
        numberOfLevels: 1,
        kgPerShelf: 0,
        frameMaterial: 'Steel',
        frameCoating: 'Powder Coated',
        shelfType: 'Steel Panels',
        compatibleShelfSku: null,
      },
    ],
  },
]
